### ISSUE TITLE
Parser misses throws tag if no description

### ISSUE THREAD

**Issue by arobie1992** [chhorz/javadoc-parser#19]
I'm working on a small project that's using this parser to find the exceptions listed in a javadoc comment. I ran into a situation where it was missing declared `@throws` tags if there was no description. For example, this works fine:

    /**
     * @throws RuntimeException if something goes wrong
     */
    public void foo();

However this doesn't:

    /**
     * @throws RuntimeException
     */
    public void foo();

I know it's a best practice to always provide a description in the throws annotation, but given that it's not a hard requirement, it seems like it would make sense to still retrieve this with either a null or empty description.

**Comment by arobie1992** [comment]
Did a little poking around and it seems to be the regex. `@throws\s+?(?<className>.+?)\s+?(?<description>.+?)\s*(?=@author|@category|@deprecated|@exception|@param|@return|@see|@since|@throws|@version|[^{]@\S+|$)`

I did a little playing around in a regex tester and it seems like this modification fixes at least this scenario. `@throws\s+?(?<className>.+?)(?:\s+(?<description>.+))?`. Instead of having optional for both the space and the descrption, it wraps the space and descrption in a non-capturing group that is optional. Let me know if this change sounds reasonable to you, and if so I can see about submitting a PR sometime soon.

**Comment by chhorz** [comment]
Hi @arobie1992 ,

thank you for reporting this issue. 

I did some rework on the internal structure and came up with a new snaphot version: *0.2.0-SNAPSHOT*. Can you please try if this version fixes your issue?

At the moment the new version still needs some documentation an code clean-up but it should work.

**Comment by arobie1992** [comment]
Hi @chhorz, looks like it's not available in Maven central just yet. Is it available elsewhere for direct download—I'm fine with doing system scope for the time being—or should I wait until it shows up in Maven?

**Comment by chhorz** [comment]
The snapshot builds are available in the following sonatype repository:

```xml
<repositories>
    <repository>
        <id>ossrh</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

This repository is not syncronized with Maven central - so the snapshots won´t be listed there.

**Comment by arobie1992** [comment]
I updated the pom to include the repo but it still doesn't seem to be able to find 0.2.0-SNAPSHOT. I was able to find a 0.1.2-SNAPSHOT. Will that work?

**Comment by chhorz** [comment]
I am sorry - there was an issue with the GitHub action that should publish the snapshots. Now a 0.2.0-SNAPSHOT version should be available ([see here](https://oss.sonatype.org/content/repositories/snapshots/com/github/chhorz/javadoc-parser/0.2.0-SNAPSHOT/)).
