### ISSUE TITLE
Add support new java 18 snippet tag

### ISSUE THREAD

**Issue by altro3** [chhorz/javadoc-parser#25]
Hi! Good tool, thanks for this! :-) In JDK 18 a new snippet tag has been added (see https://openjdk.org/jeps/413)

**Comment by chhorz** [comment]
Hi, thanks for your feature request. 

I am working on this issue and it might be ready for testing soon.

**Comment by chhorz** [comment]
Hi, could you please try the feature in the current snapshot and give me feed back about it?

Maven Dependency:
```xml
<dependency>
	<groupId>com.github.chhorz</groupId>
	<artifactId>javadoc-parser</artifactId>
        <version>0.3.0-SNAPSHOT</version>
</dependency>
```
Link to Sonatype repository for download: [javadoc-parser / 0.3.0-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/github/chhorz/javadoc-parser/0.3.0-SNAPSHOT/)

**Comment by altro3** [comment]
@chhorz Hi! Sure, today or tomorrrow

**Comment by altro3** [comment]
@chhorz Well, while I have not looked at the implementation of the snippet tag, but I have looked at what tags are generally found in javadoc and kotlindoc . Here's what we managed to find out (I could be wrong about something, so please check):

1. Currently supported tags:
```
@author
@deprecated
@category
@since
@throws
@see
@return
@param
@exception
@version
@snippet (your last changes)
```

2. `@category` tag is not supproted in java. This is just proposed tag (see https://www.oracle.com/java/technologies/javase/proposed-javadoc-tags.html)

3. Unsupported javadoc tags:
```
@code
@docRoot
@inheritDoc
@link
@linkplain
@serial
@serialData
@serialField
@value
```

3. Unsupported kotlin tags:
```
@sample
@suppress
@constructor
@receiver
@property
```

It would be cool to add support for missing tags, including for Kotlin. To make it clear why your project is interesting to me: I used your library for one of the micronaut framework modules (see https://github.com/micronaut-projects/micronaut-openapi/pull/761). For this reason, it would be great to add kotlin support. And again, I repeat: great work! Much needed library!

**Comment by altro3** [comment]
@chhorz Hi! I tried yor new library version - it works! Could you read my last comment? What do you think? Can you add support for missing tags to be fully compatible with all standard java and kotlin tags?

**Comment by chhorz** [comment]
Hi @altro3 ,

i am sorry for the long delay on this topic. I just published a new snapshot that includes the missing Javadoc and KDoc tags. 

Currently the KDoc syntax for parameter with square brackets is not supported (`@param[name] some description`)

Maybe you could try the new version.

**Comment by altro3** [comment]
@chhorz Hi ! No problem. It's very cool that you added support for all tags. I wrote my comment in the pull request. In the rest - everything is fine. About `@param[name]` - doesn't matter. The main thing is that your library now understands that there is a property tag

**Comment by chhorz** [comment]
The version 0.3.0 was released yesterday and should not be available on maven central.

**Comment by altro3** [comment]
@chhorz thanks! Good job! :-)
