### ISSUE TITLE
Difference with version 0.2.0

### ISSUE THREAD

**Issue by altro3** [chhorz/javadoc-parser#29]
@chhorz Hi!

Problem with parsing in version 0.3.0. My test failed after upgrade to version 0.3.0.

My javadoc:
```
{@summary This is a summary text.} This is a description with <b>bold</b> and {@code some code}

@since 1.0
@param foo The foo param
@param bar The {@code bar} param
@return The {@value return} value

In version 0.2.0 the result was (after convert html to md):
```
methodSummary: This is a summary text.
methodDescription: This is a description with **bold** and `some code`
parameters: bar -> The `bar` param, foo -> The foo param
returnDescription: The return value
```

In version 0.3.0 the result is (after convert html to md):
```
methodSummary: This is a summary text.
methodDescription: {@summary This is a summary text.} This is a description with **bold** and `some code`
parameters: bar -> The `bar` param, foo -> The foo param
returnDescription: The return value

Why `This is a description with **bold** and some code` was changed to `{@summary This is a summary text.} This is a description with **bold** and some code`

Is it right?

**Comment by altro3** [comment]
I think, need to remove summary block or remove summary tag. Must be:
`This is a description with **bold** and some code` or `This is a summary text. This is a description with **bold** and some code`

**Comment by chhorz** [comment]
Hi @altro3 ,

i tried to reconstruct your example and got the following result:

* Version 0.1.1 and Version 0.2.0
`getSummary()` -> This is a summary text.
`getDescription()` -> This is a summary text. This is a description with <b>bold</b> and `some code`
* Version 0.3.0
`getSummary()` -> This is a summary text.
`getDescription()` -> {@summary This is a summary text.} This is a description with <b>bold</b> and `some code`

So i think the content of the summary block was always present in the description field. But you are right - the inline tag of the summary should be removed.

**Comment by altro3** [comment]
Yes, the main problem is that the summary tag is not removed from the documentation

**Comment by chhorz** [comment]
The issue was that inline tags where not removed when they are at the first position of the description. I will release an updated version now. The release should be available on maven central later this day.
